[mysql]
  dbname="collage"
  host="db"
  port="3306"
  user="collage"
  pass="collagepass"
  sslmode="false"

output = "internal/infrastructure/models"
pkgname = "models"
wipe = true
no-tests = true
no-hooks = false
no-auto-timestamps = false
