// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CollageResults             string
	CollagesTemplate           string
	DeviceTokens               string
	Friends                    string
	GroupMembers               string
	GroupPartAssignments       string
	Groups                     string
	ResultDownload             string
	TemplateParts              string
	UploadImages               string
	UploadImagesCollageResults string
	Users                      string
}{
	CollageResults:             "collage_results",
	CollagesTemplate:           "collages_template",
	DeviceTokens:               "device_tokens",
	Friends:                    "friends",
	GroupMembers:               "group_members",
	GroupPartAssignments:       "group_part_assignments",
	Groups:                     "groups",
	ResultDownload:             "result_download",
	TemplateParts:              "template_parts",
	UploadImages:               "upload_images",
	UploadImagesCollageResults: "upload_images_collage_results",
	Users:                      "users",
}
