// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("CollageResults", testCollageResultsUpsert)

	t.Run("CollagesTemplates", testCollagesTemplatesUpsert)

	t.Run("DeviceTokens", testDeviceTokensUpsert)

	t.Run("Friends", testFriendsUpsert)

	t.Run("GroupMembers", testGroupMembersUpsert)

	t.Run("GroupPartAssignments", testGroupPartAssignmentsUpsert)

	t.Run("Groups", testGroupsUpsert)

	t.Run("ResultDownloads", testResultDownloadsUpsert)

	t.Run("TemplateParts", testTemplatePartsUpsert)

	t.Run("UploadImages", testUploadImagesUpsert)

	t.Run("UploadImagesCollageResults", testUploadImagesCollageResultsUpsert)

	t.Run("Users", testUsersUpsert)
}
